/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as WriteRouteImport } from './routes/write'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as GameChapterIndexRouteImport } from './routes/game/$chapter/index'
import { Route as GameChapterStageRouteImport } from './routes/game/$chapter/$stage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GameChapterIndexRoute = GameChapterIndexRouteImport.update({
  id: '/game/$chapter/',
  path: '/game/$chapter/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameChapterStageRoute = GameChapterStageRouteImport.update({
  id: '/game/$chapter/$stage',
  path: '/game/$chapter/$stage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/browse': typeof BrowseRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/write': typeof WriteRoute
  '/game/': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/$chapter/': typeof GameChapterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/browse': typeof BrowseRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/write': typeof WriteRoute
  '/game': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/$chapter': typeof GameChapterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/browse': typeof BrowseRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/write': typeof WriteRoute
  '/game/': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/$chapter/': typeof GameChapterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alphabet'
    | '/browse'
    | '/drill'
    | '/guide'
    | '/login'
    | '/quiz'
    | '/write'
    | '/game/'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/$chapter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alphabet'
    | '/browse'
    | '/drill'
    | '/guide'
    | '/login'
    | '/quiz'
    | '/write'
    | '/game'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/$chapter'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alphabet'
    | '/browse'
    | '/drill'
    | '/guide'
    | '/login'
    | '/quiz'
    | '/write'
    | '/game/'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/$chapter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlphabetRoute: typeof AlphabetRoute
  BrowseRoute: typeof BrowseRoute
  DrillRoute: typeof DrillRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  WriteRoute: typeof WriteRoute
  GameIndexRoute: typeof GameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GameChapterStageRoute: typeof GameChapterStageRoute
  GameChapterIndexRoute: typeof GameChapterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$chapter/': {
      id: '/game/$chapter/'
      path: '/game/$chapter'
      fullPath: '/game/$chapter/'
      preLoaderRoute: typeof GameChapterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$chapter/$stage': {
      id: '/game/$chapter/$stage'
      path: '/game/$chapter/$stage'
      fullPath: '/game/$chapter/$stage'
      preLoaderRoute: typeof GameChapterStageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlphabetRoute: AlphabetRoute,
  BrowseRoute: BrowseRoute,
  DrillRoute: DrillRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  WriteRoute: WriteRoute,
  GameIndexRoute: GameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GameChapterStageRoute: GameChapterStageRoute,
  GameChapterIndexRoute: GameChapterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
