/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as KeepRouteImport } from './routes/keep'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchRouteImport } from './routes/match'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as WriteRouteImport } from './routes/write'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as GameChapterIndexRouteImport } from './routes/game/$chapter/index'
import { Route as GameChapterStageRouteImport } from './routes/game/$chapter/$stage'
import { Route as GameAlefbetIndexRouteImport } from './routes/game/alefbet/index'
import { Route as GameAlefbetLevelRouteImport } from './routes/game/alefbet/$level'
import { Route as GameSyllablesIndexRouteImport } from './routes/game/syllables/index'
import { Route as GameSyllablesUnitRouteImport } from './routes/game/syllables/$unit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepRoute = KeepRouteImport.update({
  id: '/keep',
  path: '/keep',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GameChapterIndexRoute = GameChapterIndexRouteImport.update({
  id: '/game/$chapter/',
  path: '/game/$chapter/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameChapterStageRoute = GameChapterStageRouteImport.update({
  id: '/game/$chapter/$stage',
  path: '/game/$chapter/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const GameAlefbetIndexRoute = GameAlefbetIndexRouteImport.update({
  id: '/game/alefbet/',
  path: '/game/alefbet/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameAlefbetLevelRoute = GameAlefbetLevelRouteImport.update({
  id: '/game/alefbet/$level',
  path: '/game/alefbet/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSyllablesIndexRoute = GameSyllablesIndexRouteImport.update({
  id: '/game/syllables/',
  path: '/game/syllables/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSyllablesUnitRoute = GameSyllablesUnitRouteImport.update({
  id: '/game/syllables/$unit',
  path: '/game/syllables/$unit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/browse': typeof BrowseRoute
  '/challenge': typeof ChallengeRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/keep': typeof KeepRoute
  '/leaderboard': typeof LeaderboardRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/quiz': typeof QuizRoute
  '/rewards': typeof RewardsRoute
  '/write': typeof WriteRoute
  '/game/': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/alefbet/$level': typeof GameAlefbetLevelRoute
  '/game/syllables/$unit': typeof GameSyllablesUnitRoute
  '/game/$chapter/': typeof GameChapterIndexRoute
  '/game/alefbet/': typeof GameAlefbetIndexRoute
  '/game/syllables/': typeof GameSyllablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/browse': typeof BrowseRoute
  '/challenge': typeof ChallengeRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/keep': typeof KeepRoute
  '/leaderboard': typeof LeaderboardRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/quiz': typeof QuizRoute
  '/rewards': typeof RewardsRoute
  '/write': typeof WriteRoute
  '/game': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/alefbet/$level': typeof GameAlefbetLevelRoute
  '/game/syllables/$unit': typeof GameSyllablesUnitRoute
  '/game/$chapter': typeof GameChapterIndexRoute
  '/game/alefbet': typeof GameAlefbetIndexRoute
  '/game/syllables': typeof GameSyllablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/browse': typeof BrowseRoute
  '/challenge': typeof ChallengeRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/keep': typeof KeepRoute
  '/leaderboard': typeof LeaderboardRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/quiz': typeof QuizRoute
  '/rewards': typeof RewardsRoute
  '/write': typeof WriteRoute
  '/game/': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/alefbet/$level': typeof GameAlefbetLevelRoute
  '/game/syllables/$unit': typeof GameSyllablesUnitRoute
  '/game/$chapter/': typeof GameChapterIndexRoute
  '/game/alefbet/': typeof GameAlefbetIndexRoute
  '/game/syllables/': typeof GameSyllablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alphabet'
    | '/browse'
    | '/challenge'
    | '/drill'
    | '/guide'
    | '/keep'
    | '/leaderboard'
    | '/listen'
    | '/login'
    | '/match'
    | '/quiz'
    | '/rewards'
    | '/write'
    | '/game/'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/alefbet/$level'
    | '/game/syllables/$unit'
    | '/game/$chapter/'
    | '/game/alefbet/'
    | '/game/syllables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alphabet'
    | '/browse'
    | '/challenge'
    | '/drill'
    | '/guide'
    | '/keep'
    | '/leaderboard'
    | '/listen'
    | '/login'
    | '/match'
    | '/quiz'
    | '/rewards'
    | '/write'
    | '/game'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/alefbet/$level'
    | '/game/syllables/$unit'
    | '/game/$chapter'
    | '/game/alefbet'
    | '/game/syllables'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alphabet'
    | '/browse'
    | '/challenge'
    | '/drill'
    | '/guide'
    | '/keep'
    | '/leaderboard'
    | '/listen'
    | '/login'
    | '/match'
    | '/quiz'
    | '/rewards'
    | '/write'
    | '/game/'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/alefbet/$level'
    | '/game/syllables/$unit'
    | '/game/$chapter/'
    | '/game/alefbet/'
    | '/game/syllables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlphabetRoute: typeof AlphabetRoute
  BrowseRoute: typeof BrowseRoute
  ChallengeRoute: typeof ChallengeRoute
  DrillRoute: typeof DrillRoute
  GuideRoute: typeof GuideRoute
  KeepRoute: typeof KeepRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ListenRoute: typeof ListenRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  QuizRoute: typeof QuizRoute
  RewardsRoute: typeof RewardsRoute
  WriteRoute: typeof WriteRoute
  GameIndexRoute: typeof GameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GameChapterStageRoute: typeof GameChapterStageRoute
  GameAlefbetLevelRoute: typeof GameAlefbetLevelRoute
  GameSyllablesUnitRoute: typeof GameSyllablesUnitRoute
  GameChapterIndexRoute: typeof GameChapterIndexRoute
  GameAlefbetIndexRoute: typeof GameAlefbetIndexRoute
  GameSyllablesIndexRoute: typeof GameSyllablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keep': {
      id: '/keep'
      path: '/keep'
      fullPath: '/keep'
      preLoaderRoute: typeof KeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$chapter/': {
      id: '/game/$chapter/'
      path: '/game/$chapter'
      fullPath: '/game/$chapter/'
      preLoaderRoute: typeof GameChapterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$chapter/$stage': {
      id: '/game/$chapter/$stage'
      path: '/game/$chapter/$stage'
      fullPath: '/game/$chapter/$stage'
      preLoaderRoute: typeof GameChapterStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/alefbet/': {
      id: '/game/alefbet/'
      path: '/game/alefbet'
      fullPath: '/game/alefbet/'
      preLoaderRoute: typeof GameAlefbetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/alefbet/$level': {
      id: '/game/alefbet/$level'
      path: '/game/alefbet/$level'
      fullPath: '/game/alefbet/$level'
      preLoaderRoute: typeof GameAlefbetLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/syllables/': {
      id: '/game/syllables/'
      path: '/game/syllables'
      fullPath: '/game/syllables/'
      preLoaderRoute: typeof GameSyllablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/syllables/$unit': {
      id: '/game/syllables/$unit'
      path: '/game/syllables/$unit'
      fullPath: '/game/syllables/$unit'
      preLoaderRoute: typeof GameSyllablesUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlphabetRoute: AlphabetRoute,
  BrowseRoute: BrowseRoute,
  ChallengeRoute: ChallengeRoute,
  DrillRoute: DrillRoute,
  GuideRoute: GuideRoute,
  KeepRoute: KeepRoute,
  LeaderboardRoute: LeaderboardRoute,
  ListenRoute: ListenRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  QuizRoute: QuizRoute,
  RewardsRoute: RewardsRoute,
  WriteRoute: WriteRoute,
  GameIndexRoute: GameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GameChapterStageRoute: GameChapterStageRoute,
  GameAlefbetLevelRoute: GameAlefbetLevelRoute,
  GameSyllablesUnitRoute: GameSyllablesUnitRoute,
  GameChapterIndexRoute: GameChapterIndexRoute,
  GameAlefbetIndexRoute: GameAlefbetIndexRoute,
  GameSyllablesIndexRoute: GameSyllablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
